#!/bin/bash

HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg

HAPROXY_GLOBAL_MAX_CONNECTIONS=$(etcdctl get /config/HAPROXY_GLOBAL_MAX_CONNECTIONS || echo "50000")
HAPROXY_DEFAULTS_MAX_CONNECTIONS=$(etcdctl get /config/HAPROXY_DEFAULTS_MAX_CONNECTIONS || echo "25000")
HAPROXY_DEFAULTS_RETRIES=$(etcdctl get /config/HAPROXY_DEFAULTS_RETRIES || echo "3")
HAPROXY_DEFAULTS_TIMEOUT_HTTP_REQUEST=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_HTTP_REQUEST || echo "10s")
HAPROXY_DEFAULTS_TIMEOUT_CLIENT=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_CLIENT || echo "1m")
HAPROXY_DEFAULTS_TIMEOUT_CONNECT=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_CONNECT || echo "10s")
HAPROXY_DEFAULTS_TIMEOUT_SERVER=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_SERVER || echo "1m")
HAPROXY_DEFAULTS_TIMEOUT_QUEUE=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_QUEUE || echo "1m")
HAPROXY_DEFAULTS_TIMEOUT_HTTP_KEEP_ALIVE=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_HTTP_KEEP_ALIVE || echo "10s")
HAPROXY_DEFAULTS_OPTION_HTTPCHK=$(etcdctl get /config/HAPROXY_DEFAULTS_OPTION_HTTPCHK || echo "/healthcheck")
HAPROXY_DEFAULTS_TIMEOUT_CHECK=$(etcdctl get /config/HAPROXY_DEFAULTS_TIMEOUT_CHECK || echo "5s")
HAPROXY_DEFAULTS_SPREAD_CHECKS=$(etcdctl get /config/HAPROXY_DEFAULTS_SPREAD_CHECKS || echo "5")
HAPROXY_DEFAULTS_MONITOR_URI=$(etcdctl get /config/HAPROXY_DEFAULTS_MONITOR_URI || echo "/monitor")
HAPROXY_STATS_PORT=$(etcdctl get /config/HAPROXY_STATS_PORT || echo "8080")
HAPROXY_STATS_ENABLE=$(etcdctl get /config/HAPROXY_STATS_ENABLE || echo "enable")
HAPROXY_STATS_URI=$(etcdctl get /config/HAPROXY_STATS_URI || echo "/stats")
HAPROXY_STATS_REALM=$(etcdctl get /config/HAPROXY_STATS_REALM || echo "Statistics")
HAPROXY_STATS_USERNAME=$(etcdctl get /config/HAPROXY_STATS_USERNAME || echo "username")
HAPROXY_STATS_PASSWORD=$(etcdctl get /config/HAPROXY_STATS_PASSWORD || echo "password")

sed -i -e "s/HAPROXY_GLOBAL_MAX_CONNECTIONS/${HAPROXY_GLOBAL_MAX_CONNECTIONS}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_MAX_CONNECTIONS/${HAPROXY_DEFAULTS_MAX_CONNECTIONS}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_RETRIES/${HAPROXY_DEFAULTS_RETRIES}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_HTTP_REQUEST/${HAPROXY_DEFAULTS_TIMEOUT_HTTP_REQUEST}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_CLIENT/${HAPROXY_DEFAULTS_TIMEOUT_CLIENT}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_CONNECT/${HAPROXY_DEFAULTS_TIMEOUT_CONNECT}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_SERVER/${HAPROXY_DEFAULTS_TIMEOUT_SERVER}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_QUEUE/${HAPROXY_DEFAULTS_TIMEOUT_QUEUE}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_HTTP_KEEP_ALIVE/${HAPROXY_DEFAULTS_TIMEOUT_HTTP_KEEP_ALIVE}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_OPTION_HTTPCHK/${HAPROXY_DEFAULTS_OPTION_HTTPCHK}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_TIMEOUT_CHECK/${HAPROXY_DEFAULTS_TIMEOUT_CHECK}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_SPREAD_CHECKS/${HAPROXY_DEFAULTS_SPREAD_CHECKS}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_DEFAULTS_MONITOR_URI/${HAPROXY_DEFAULTS_MONITOR_URI}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_PORT/${HAPROXY_STATS_PORT}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_ENABLE/${HAPROXY_STATS_ENABLE}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_URI/${HAPROXY_STATS_URI}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_REALM/${HAPROXY_STATS_REALM}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_USERNAME/${HAPROXY_STATS_USERNAME}/g" $HAPROXY_CONFIG
sed -i -e "s/HAPROXY_STATS_PASSWORD/${HAPROXY_STATS_PASSWORD}/g" $HAPROXY_CONFIG

